cc_library(
	name = "stock-observer",
	srcs = glob(["*.cc"]),
	hdrs = glob(["*.h"]),
	copts = ["-std=c++17", "-Wall", "-Wextra", "-Weffc++", "-Wno-non-virtual-dtor", "-Wno-unused-parameter"],
	visibility = ["//test:__pkg__"],
)
